/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const SOSAlert = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'user' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'location' : IDL.Opt(Location),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MissingPerson = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Bool,
  'name' : IDL.Text,
  'emergencyContact' : IDL.Text,
  'description' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'reporter' : IDL.Principal,
  'lastSeen' : IDL.Int,
  'lastSeenLocation' : Location,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'emergencyContact' : IDL.Text,
  'phone' : IDL.Text,
});
export const GroupMember = IDL.Record({
  'status' : IDL.Text,
  'active' : IDL.Bool,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'location' : IDL.Opt(Location),
});
export const Group = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'members' : IDL.Vec(GroupMember),
  'name' : IDL.Text,
  'groupCode' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGroup' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getActiveSOSAlerts' : IDL.Func([], [IDL.Vec(SOSAlert)], ['query']),
  'getAllMissingPersons' : IDL.Func([], [IDL.Vec(MissingPerson)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGroup' : IDL.Func([IDL.Text], [Group], ['query']),
  'getGroupMembers' : IDL.Func([IDL.Text], [IDL.Vec(GroupMember)], ['query']),
  'getGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getMissingPerson' : IDL.Func([IDL.Nat], [IDL.Opt(MissingPerson)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGroup' : IDL.Func([IDL.Text, IDL.Text], [Group], []),
  'markMissingPersonFound' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'reportMissingPerson' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'resolveSOSAlert' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchMissingPersonsByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MissingPerson)],
      ['query'],
    ),
  'triggerSOSAlert' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Float64), IDL.Opt(IDL.Float64), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'updateLocation' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Location = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const SOSAlert = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'user' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'location' : IDL.Opt(Location),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MissingPerson = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Bool,
    'name' : IDL.Text,
    'emergencyContact' : IDL.Text,
    'description' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'reporter' : IDL.Principal,
    'lastSeen' : IDL.Int,
    'lastSeenLocation' : Location,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'emergencyContact' : IDL.Text,
    'phone' : IDL.Text,
  });
  const GroupMember = IDL.Record({
    'status' : IDL.Text,
    'active' : IDL.Bool,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'location' : IDL.Opt(Location),
  });
  const Group = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'members' : IDL.Vec(GroupMember),
    'name' : IDL.Text,
    'groupCode' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGroup' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getActiveSOSAlerts' : IDL.Func([], [IDL.Vec(SOSAlert)], ['query']),
    'getAllMissingPersons' : IDL.Func([], [IDL.Vec(MissingPerson)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGroup' : IDL.Func([IDL.Text], [Group], ['query']),
    'getGroupMembers' : IDL.Func([IDL.Text], [IDL.Vec(GroupMember)], ['query']),
    'getGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getMissingPerson' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MissingPerson)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGroup' : IDL.Func([IDL.Text, IDL.Text], [Group], []),
    'markMissingPersonFound' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'reportMissingPerson' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'resolveSOSAlert' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchMissingPersonsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MissingPerson)],
        ['query'],
      ),
    'triggerSOSAlert' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'updateLocation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };