/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Group {
  'id' : string,
  'creator' : Principal,
  'members' : Array<GroupMember>,
  'name' : string,
  'groupCode' : string,
}
export interface GroupMember {
  'status' : string,
  'active' : boolean,
  'userId' : Principal,
  'name' : string,
  'location' : [] | [Location],
}
export interface Location {
  'lat' : number,
  'lng' : number,
  'description' : string,
  'timestamp' : bigint,
}
export interface MissingPerson {
  'id' : bigint,
  'status' : boolean,
  'name' : string,
  'emergencyContact' : string,
  'description' : string,
  'photo' : [] | [ExternalBlob],
  'reporter' : Principal,
  'lastSeen' : bigint,
  'lastSeenLocation' : Location,
}
export interface SOSAlert {
  'id' : bigint,
  'active' : boolean,
  'user' : Principal,
  'message' : string,
  'timestamp' : bigint,
  'location' : [] | [Location],
}
export interface UserProfile {
  'name' : string,
  'emergencyContact' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGroup' : ActorMethod<[string], string>,
  'getActiveSOSAlerts' : ActorMethod<[], Array<SOSAlert>>,
  'getAllMissingPersons' : ActorMethod<[], Array<MissingPerson>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGroup' : ActorMethod<[string], Group>,
  'getGroupMembers' : ActorMethod<[string], Array<GroupMember>>,
  'getGroups' : ActorMethod<[], Array<Group>>,
  'getMissingPerson' : ActorMethod<[bigint], [] | [MissingPerson]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinGroup' : ActorMethod<[string, string], Group>,
  'markMissingPersonFound' : ActorMethod<[bigint], boolean>,
  'reportMissingPerson' : ActorMethod<
    [string, number, number, string, string, [] | [ExternalBlob]],
    bigint
  >,
  'resolveSOSAlert' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchMissingPersonsByName' : ActorMethod<[string], Array<MissingPerson>>,
  'triggerSOSAlert' : ActorMethod<
    [string, [] | [number], [] | [number], [] | [string]],
    bigint
  >,
  'updateLocation' : ActorMethod<[string, number, number, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];